on:
  push:
    branches: [trunk]
  schedule:
    - cron: "0 21 * * */3"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install dependencies
        run: shards install
      - name: Run specs
        run: crystal spec
      - name: Check formatting
        run: crystal tool format --check
